name: PII Scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: .

    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@v3.2.0
      with:
        entryPoint: 'trufflehog'
        args: 'filesystem --directory . --rules-file pii-rules.json --json --jsonfile results.json'

    - name: Print results
      run: cat results.json
